version: "3.8"
services:
  postgres:
    image: ksisoft/pgvector:16.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=manaql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=vector
      -c max_connections=50
      -c shared_buffers=128MB
      -c effective_cache_size=512MB
      -c maintenance_work_mem=128MB
      -c work_mem=8MB
      -c random_page_cost=1.1
      -c effective_io_concurrency=100
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d manaql"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
